server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.150.3:8848   # nacos服务器地址
    gateway:
      routes:
        - id: user
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: order
          uri: lb://orderservice
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=token, d0391ecb   # 添加请求头
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决CORS的options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              # - "*"
              - "http://192.168.150.3:8800"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"     # 允许在请求中携带的头信息
            allowCredentials: true  # 是否允许携带cookie
            maxAge: 360000          # 这次跨域检测的有效期。因为每次都会CORS询问，耗费性能，故而有效期内让其不再询问。
logging:
  level:
    com.com.sword: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS