server:
  port: 8081
spring:
  application:
    name: userservice # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.150.3:8848   # nacos服务器地址
      discovery:
        cluster-name: HZ
logging:
  level:
    com.sword: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS