server:
  port: 8080
spring:
  application:
    name: orderservice

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

logging:
  level:
    com.com.sword: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS